
apiVersion: v1
kind: Service
metadata:
  name: content-service
  labels:
    app: ott-platform
    service: content
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: content-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  labels:
    app: ott-platform
    service: content
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: ott-platform/content-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: CONTENT_DB_HOST
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: db-host
        - name: CONTENT_DB_USER
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: db-user
        - name: CONTENT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: db-password
        - name: CONTENT_DB_NAME
          value: "ott_content"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: aws-secret-access-key
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: aws-s3-bucket
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
