
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: ott-platform
    service: admin
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
  selector:
    app: admin-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: ott-platform
    service: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: ott-platform/admin-service:latest
        ports:
        - containerPort: 3006
        env:
        - name: NODE_ENV
          value: "production"
        - name: AUTH_DB_HOST
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: db-host
        - name: AUTH_DB_USER
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: db-user
        - name: AUTH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: db-password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ott-secrets
              key: aws-secret-access-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5
